security:
  oauth2:
    client:
      clientId: 228K8J
      clientSecret: 7f4fa0aef21db48ce15f27110f3fd771
      accessTokenUri: https://api.fitbit.com/oauth2/token
      userAuthorizationUri: https://www.fitbit.com/oauth2/authorize
      tokenName: oauth_token
      authenticationScheme: header
      clientAuthenticationScheme: header
      scope: "activity heartrate location nutrition profile settings sleep social weight"
    resource:
      userInfoUri: https://api.fitbit.com/1/user/-/profile.json
fitbit:
  api:
    resource:
      activitiesUri: https://api.fitbit.com/1/user/-/activities.json

logging:
  level:
    org.springframework.security: TRACE
